### ISSUE TITLE
Bar position using numbers.

### ISSUE THREAD

**Issue by PuckAlive** [talimity/MPTimer#1]
First of all, thank you you beautiful human bean. This will help an awful lot with AoE rotations.

Can we get a way to position the bar using numbers, a la HudMan or JobBars? Thank you!

**Comment by talimity** [comment]
No problem!  I got this working today so I'll push it up soon once I can implement a couple other things I've been meaning to add.

**Comment by talimity** [comment]
Resolved in c6102e326c1d73421f569ddbf9f311a54bf3d748
